AWSTemplateFormatVersion: "2010-09-09"
Description: Create ECR
Parameters:
  ProjectName:
    Type: String
    Description: Project name
Resources:
  ECR:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub ${ProjectName}-ecr
