name: Deploy to production environment

on:
  push:
    branches:
      # - master
      #TODO 一時的にワークフローを動かさないように main に設定しているだけ
      - main
    paths-ignore:
      - "notes/**"
  # workflow_dispatch:
  #   region:
  #     description: "AWS Region to deploy to"
  #     required: true
  #     default: "ap-northeast-1"
  #   ProjectName:
  #     description: "AWS Region to deploy to"
  #     required: true
  #     default: "test-project"

jobs:
  deploy:
    name: Deploy to production environment
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to production environment
        run: |
          echo "Hello, World!\nI'm deploying..."
      - name: Notify to Discord
        uses: sarisia/actions-status-discord@v1 # https://github.com/sarisia/actions-status-discord
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          username: GitHub Actions
          status: ${{ job.status }}
          nofail: false # when notification failed, this action failed, then workflow failed
